# .goreleaser.yml
version: 2

project_name: go-mail-ru-client

builds:
  - id: go-mail-ru-client
    main: .
    binary: go-mail-ru-client
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

release:
  github:
    owner: mentatxx
    name: go-mail-ru-client
